export const phoneAction={
    PHONES_LOADED:'PHONES_LOADED',
    PHONE_ADDED_TO_CART:'PHONE_ADDED_TO_CART',
    REMOVE_PHONE_TO_CART:'REMOVE_PHONE_TO_CART',
    DECREMENT_PHONE_TO_CART:'DECREMENT_PHONE_TO_CART'
};